sudo: false
dist: trusty

cache:
  apt: true

env:
  global:
      - SPHINXBUILD=~/.local/bin/sphinx-build
      - DIFF_COMMIT=v0.1

git:
  depth: false

addons:
  apt:
    packages:
      - python-pip
      - latexmk
      - libalgorithm-diff-perl
      - texlive
      - texlive-latex-extra
      - texlive-humanities
      - texlive-generic-recommended
      - graphviz
      - texlive-generic-extra

install:
  - pip install --user mako
  - pip install --user Sphinx
  - pip install --user codespell

before_script:
  - wget https://github.com/ftilmann/latexdiff/releases/download/1.2.1/latexdiff-1.2.1.tar.gz
  - tar xvf latexdiff-1.2.1.tar.gz
  - export PATH=$PWD/latexdiff-1.2.1/:$PATH

script:
  - make check
  - git checkout $DIFF_COMMIT
  - make latexpdf
  - mv build/latex build/latex-previous
  - git checkout $TRAVIS_COMMIT
  - make latexpdf
  - make latexdiff
  - make html
  - make singlehtml

before_deploy:
  - cp build/latex/devicetree-specification.pdf build/devicetree-specification-$TRAVIS_TAG.pdf
  - cp build/latex/devicetree-specification-changebars.pdf build/devicetree-specification-changebars-$TRAVIS_TAG.pdf

deploy:
  - provider: releases
    prerelease: false
    api_key:
      # Rob's OAuth token
      secure: hXWsZWHQwJCxU9QqZ+63IZGesBJ8+BOSzI0y+dUv3aEdVc8EKUtNXwxFBnSz/1NxWCU06Jhk8VfZnHs0ihBSjgmWXKrbz8kMN4OJM0th/nXqVNcbpeX4c11CaMQ2/SZaD8KGbcAARpPZMFm38l+ijxe57BbLNQqdxlZ6ccYeyE2zvAft8dXUuCf/bBjhwziWQtKB9dnlXuyZA/JdxUd9rdolr98R/OmXGJWfssmkgsRS8B+zPN0MeyvRrVcJb8VdOwu9u5IXd76tupb4hwV6yScfiOLND9yU1fUjK1iipjyo14GexCVNMuDMurmynsIBZpxFe0GpFKYXocvQgcxox8x7uvAICe5sCvU5YPIOKXg0Eecz28kE6V8jdqE2oWXLw4CsyheK+GeRxmBgfZdhqka8pJ/+66pxpgIUPfkc8tsuaizrYM/8meCiwHunwfVze4ZzTCEYXCWSyV3cOoDnSn+OfYiAuappA2sjWcx2qQDd9r310PP1ty1dOVATX+yIT3YHSy5ucROAgSCehwxdUMj3gHGxzietsk5txTRTwVQH4iAuyQzeef7earXTF6o4uCmRjVbcACQRDmgiPw6BBU5Sh+BZoVWm7OwqxZbOUVOdzrDN1dzDnlwbEPbHDiXfk3FcBUziCJHcGpqIG5IXKz1XK+IuLzHFYQfRiPUh1kI=
      # Grant's OAuth token
      #secure: OTxLflWvVCKQAdBOMMKIl/M1QQOrJ8QpY9I5hAjGbgrJ0YLurqhHwHXEPU2UFiv85hJRNnUGHRzaU4XRNleKS4QKz5O6WiXo9opgivxILBKodcSPOwxyZioFOGmppgygOFSvHeN+x1TM7MBhHrhUuZiReIndad0LV5lxp5byupJixss2FakAPUgD9bRuXSnwbrVmQUl639/xuU6I7cV6NBebs0Ic/mZAbHRyh427oxw6jMxm0nlMelLL8l7Np7FOxDMMPbIYC3TTY4XkZPnLZ8iA4pfhtPH3MaHFE/9mCC7AEt01C44vLPrQ4/h5MYNszof0tS6dbNDngX684SIm8dcXIB/8ahyZ0t8Lj46NlkOe+eiT9lswpCQ6uIUEhvvng0rUcQ68yi3pEmScn8af2AutpiHpeDIg0Gxtgdrq+S/psWIXxqZ/dRZXUl6rVv3su8Y0ejL7LIcFJFjKNVgXWC1LopxYX7BOe7LtzdAmT5RpNvrVq0lIgDcRPZ68lhFO5VcWEKbf6e61wR3Uf6ePuT2/wzc3Yc6+5JKxMCi9JSH41u+17QK7CAR2D8mkd0qfVNQMlGOmLMsDtHg5KuPvcx0ZOLJRmEseiR18KxR2tIoGcYcZV5HWsMqfK0PYrp9Wjnq55puxvtrTuXZGi6vNH/0awPHZukbVJdPOZUd2ji0=
    file_glob: true
    file:
      - "build/devicetree-specification-*.pdf"
    skip_cleanup: true
    on:
      repo: devicetree-org/devicetree-specification
      tags: true
      branch: master
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: "build/singlehtml"
    skip_cleanup: true
    on:
      branch: master
